version: '2'

services:
  server:
    container_name: back-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - mynetwork
  db:
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: