name: Deploy runner back-olimp

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          clean: false
      - name: docker-compose
        run: docker compose up -d